name: deploy

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: production
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: install packages
        run: npm ci

      - name: build
        run: npm run build

      - name: sync
        # terraformでの値と一致している必要あり
        # build ディレクトリを 指定したバケットにアップロード
        # --delete で、同期元にないファイルを同期先から削除する
        run: aws s3 sync build s3://blogsvelte-production-39874962 --delete

      # キャッシュの無効化
      # ただしterraformからdistribution_idをもってくるのが面倒なのでいったんコメントアウト（TTLをゼロにしておく）
      # - name: Clear cache
      #   run: aws cloudfront create-invalidation --distribution-id {DISTRIBUTION_ID} --paths "/*"
