name: deploy

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: production
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: install packages
        run: npm ci

      - name: build
        run: npm run build

      - name: sync
        run: aws s3 sync build s3://blog-svelte --delete

      - name: Clear cache
        run: aws cloudfront create-invalidation --distribution-id E34RP4S1LYOKLC --paths "/*"
