name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install packages
        run: npm install
      - name: Install Playwright
        run: npx playwright install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
