name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: cache packages
        id: cache-packages
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: install packages
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: npm ci

      - name: cache build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: "**/build"
          key: ${{ runner.os }}-${{ github.sha }}

      - name: build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: npm run build
      
      - name: install playwright
        run: npx playwright install

      - name: test
        run: npm run test:ci
