name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: cache packages
        id: cache-packages
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: install packages
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: npm ci

      - name: cache svelte-kit
        id: cache-svelte-kit
        uses: actions/cache@v4
        with:
          path: "**/.svelte-kit"
          key: ${{ runner.os }}-svelte-kit-${{ github.sha }}
    
      - name: cache build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: "**/build"
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: npm run build
      
      - name: get installed playwright version
        id: playwright-version
        run: echo "version=$( npx playwright --version )" >> $GITHUB_OUTPUT

      - name: cache playwright binaries
        uses: actions/cache@v4
        id: cache-playwright
        with:
          path: ~/.cache/ms-playwright
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'

      # キャッシュがきくと適宜省略されるのでifは不要
      - name: install playwright
        run: npx playwright install

      - name: test
        run: npm run test:ci
